"""empty message

Revision ID: ff9e71f2c329
Revises: 5369015ee4e5
Create Date: 2018-11-28 13:05:24.362253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9e71f2c329'
down_revision = '5369015ee4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_image_url'), 'image', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_url'), table_name='image')
    # ### end Alembic commands ###
